### ISSUE TITLE
public dir does not contain htaccess file

### ISSUE THREAD

**Issue by huzaifaarain** [Log1x/filament-starter#45]
Hey @Log1x , First of all, thank you so much for this wonderful starter, it means a lot to get started quickly, just wondering why we haven't added the default htaccess file, I thought it might be a good idea to know the reason before submitting the PR. I just installed it, configured the vhost and couldn't get through other pages until I added the htaccess file.

**Comment by Log1x** [comment]
oversight on my part, sorry about that!
