### ISSUE TITLE
Call to undefined relationship [url] on model [Awcodes\Curator\Models\Media]

### ISSUE THREAD

**Issue by rthomas023** [Log1x/filament-starter#48]
When "toggling" the List View icon on the Media resource listing page, the following error is thrown:

Call to undefined relationship [url] on model [Awcodes\Curator\Models\Media].

![Screen Shot 2024-01-14 at 10 25 30 AM](https://github.com/Log1x/filament-starter/assets/6208519/0977f1a7-d62c-4e91-97ed-3f76ca920682)

I'm not sure if this is an issue with the Filament plugin or not as I found this:

https://github.com/awcodes/filament-curator/issues/417

**Comment by Log1x** [comment]
Interesting about `CuratorColumn` getting deprecated but I can't seem to reproduce this. I added a few images to the media library and seem to be able to toggle between List/Grid without any issues.

The only place we attempt to use `->url` is on the `figure` view component and the `post.show` full page component which are unrelated to Filament it's self.

Anything else I could try to reproduce this?

**Comment by YacoubAl-hardari** [comment]
<img width="437" alt="لقطة شاشة 2024-01-14 195434" src="https://github.com/Log1x/filament-starter/assets/94101869/8c31a8b0-7af3-4b2b-a97d-ae27e2d4bdf6">

the image does not display in sharing host

**Comment by Log1x** [comment]
Did you already link your storage on production with Artisan?

```sh
php artisan storage:link
```

If so, can you provide me the URL you are getting and what it is otherwise supposed to be?

**Comment by YacoubAl-hardari** [comment]
> Did you already link your storage on production with Artisan?
> 
> ```shell
> php artisan storage:link
> ```
> 
> If so, can you provide me the URL you are getting and what it is otherwise supposed to be?

i have added but still does not work

**Comment by YacoubAl-hardari** [comment]
yes , i did but not work 
<img width="551" alt="لقطة شاشة 2024-01-14 195935" src="https://github.com/Log1x/filament-starter/assets/94101869/54defb17-4ffc-4ae0-a205-e3448deaf4e4">

**Comment by Log1x** [comment]
Do you see the media on your server? 

What is the URL you are seeing for the broken images so we can narrow down what is potentially happening?

**Comment by YacoubAl-hardari** [comment]
the correct  URL is https://my website url /storage/media/35dc9fcc-ab53-4c6e-babe-0c28c7cd207e.png?w=40&h=40&fit=crop&fm=webp&s=e9e9bd1ed5fca2e5aa90872a555beb33

/uploader/media/35dc9fcc-ab53-4c6e-babe-0c28c7cd207e.png?w=640&h=320&fit=crop&fm=webp&s=3ad4422521f3efd3ed466c062603d18c

**Comment by YacoubAl-hardari** [comment]
I have solved this problem by changing the   'route_path' => 'Curator' to 'route_path' => 'storage'

in config file  => curator.php

**Comment by Log1x** [comment]
I'm not familiar with what `/uploader/` would be coming from. Have you edited any of the configs that would be related to this? Is it possible your server is blocking a function that is required by Glide?

Otherwise, I see `route_path` set [here](https://github.com/awcodes/filament-curator/blob/ccb90a9e6abf9c29d776506a3bc5dfd6606dc8d1/routes/web.php#L6) in Curator but I'm not sure that you'd want it to be `storage`. 🤔

**Comment by YacoubAl-hardari** [comment]
<img width="359" alt="image" src="https://github.com/Log1x/filament-starter/assets/94101869/01df299a-1cc6-4dfe-87c6-16191cf95ec2">

<img width="484" alt="لقطة شاشة 2024-01-14 201001" src="https://github.com/Log1x/filament-starter/assets/94101869/8718b7d8-0e51-4477-8609-e4c6db1122a1">

When I changed the value of 'route_path' from 'Curator' to 'storage', the functionality worked as expected. By the way, I didn't make any other edits except for the 'route_path' value change. However, I also added 'route_path' => 'uploader' to check if it would affect the path. It did change the path to 

"/uploader/media/35dc9fcc-ab53-4c6e-babe-0c28c7cd207e.png?w=640&h=320&fit=crop&fm=webp&s=3ad4422521f3efd3ed466c062603d18c".

 Then, I attempted to replace "uploader" with "storage", and this modification also produced the desired results.

**Comment by Log1x** [comment]
Appreciate you posting your solution. I haven't been able to reproduce this on my end in production but if I do I'll be sure to update this or take the necessary steps to ensure nobody else has this issue.

Going to close this for now as I feel like it is environment-specific or not entirely related to the starter.
