### ISSUE TITLE
Need To Update to newer Version

### ISSUE THREAD

**Issue by oggiesutrisna** [Log1x/filament-starter#52]
hello, I have a problem related to project installation, in the installation section I get an error that "your lock file does not contain a compatible set of packages. please run composer update", but the file is downloaded, and I need to run Composer Update to use it after the error.

what should I do?

**Comment by Log1x** [comment]
hmm the lock file was brought up in #49 – i gave my reasoning for keeping it but if it is causing issues then we can definitely get rid of it.

everything otherwise works as intended after doing `composer upgrade`?

**Comment by Log1x** [comment]
Went ahead and removed the lock files for now. Hopefully this helps!

**Comment by oggiesutrisna** [comment]
![image](https://github.com/Log1x/filament-starter/assets/40566790/2f30ebaf-5a07-42a8-aeff-4d127d47bd89)|

works so well. Thank you
