### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by Wotan6891** [Log1x/filament-starter#53]
https://filamentphp.com/plugins/shuvroroy-spatie-laravel-backup
https://filamentphp.com/plugins/joshembling-image-optimizer
https://filamentphp.com/plugins/ralphjsmit-seo
https://filamentphp.com/plugins/kenepa-translation-manager

**Comment by Log1x** [comment]
Hi!

Those plugins are great and should be quite easy to add to your project on your own. I would like to keep the starter it's self as minimal as I can out of the box.
