### ISSUE TITLE
img didn't load on post page

### ISSUE THREAD

**Issue by codename-12** [Log1x/filament-starter#68]
![Screenshot 2024-08-01 103252](https://github.com/user-attachments/assets/133b1faa-e84f-4f2d-b6f0-466835262b2f)
am i wrong in instalation ?

**Comment by Log1x** [comment]
Hi! Are the images returning valid URL's? Perhaps try `php artisan storage:link`

**Comment by codename-12** [comment]
Yes sir, I have tried it and the results are still the same, is there a pixel limit on the displayed image?
![Screenshot 2024-08-01 105220](https://github.com/user-attachments/assets/466bdcfc-b60b-4a9f-b298-f7288523f313)

**Comment by Log1x** [comment]
It looks like you might need to update `APP_URL` in your `.env`

**Comment by codename-12** [comment]
I see thanks for your help sir

**Comment by codename-12** [comment]
![image](https://github.com/user-attachments/assets/b40aaf09-07c4-42f4-a37a-554f4dd6800a)

I have tried again and it works but when I restart the server, the image doesn't appear anymore and displays an invalid URL
