### ISSUE TITLE
Class "NumberFormatter" not found

### ISSUE THREAD

**Issue by r4dhwene** [Log1x/filament-starter#8]
Hello! 
i just run the project but when i try check posts on admin i get this error : 
![error](https://github.com/Log1x/filament-starter/assets/39316906/ec824eac-70a0-4f3a-a5b8-342a72a1b770)

Class "NumberFormatter" not found

Can you help me ? thanks

**Comment by Log1x** [comment]
What are you using for your dev environment? That's from my use of the new [Number helpers](https://laravel.com/docs/10.x/helpers#numbers).

I think your error in specific is from https://www.php.net/manual/en/class.numberformatter.php

Are you missing the php-intl extension locally?

**Comment by r4dhwene** [comment]
Yes i was missing php-intel it was desactivated. thank you! and i'll try Laragon i have never used before
